### ISSUE TITLE
cryptoSignEd25519SkToSeed is not implemented

### ISSUE THREAD

**Issue by SushantChandla** [Skycoder42/libsodium_dart_bindings#4]
Can you please add that : )
[crypto_sign_ed25519_sk_to_seed](https://libsodium.gitbook.io/doc/public-key_cryptography/public-key_signatures#extracting-the-seed-and-the-public-key-from-the-secret-key)

@Skycoder42

**Comment by Skycoder42** [comment]
Sure, I can do that

**Comment by Skycoder42** [comment]
Since these methods are part of the normal sign API, it seems I must have overlooked them when initially implementing that part. Thus, I treat this as a "bug" and decided to publish this in version 1.1.2 as "patch release". Should be available on pub.dev later this day.

Thanks for pointing it out to me.

**Comment by SushantChandla** [comment]
Okay,
Thanks a bunch : )
