### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by cremfert** [Skycoder42/libsodium_dart_bindings#9]
I have setup a fresh Windows 11 virtual machine with Visual Studio 2022 CE and Flutter 2.10.
Everything works fine, but as soon as I try to build the windows app, it says:
```
CMake Error at flutter/ephemeral/.plugin_symlinks/sodium_libs/windows/CMakeLists.txt:19 (execute_process):
  execute_process error getting child return code: %1 ist keine zulässige
  Win32-Anwendung
```

Any ideas, what the problem could be?

The failing command in the CMakeLists.txt is:
```
execute_process(COMMAND "${DART}" run
                "${CMAKE_CURRENT_SOURCE_DIR}/../libsodium_version.dart"
                OUTPUT_VARIABLE LIBSODIUM_VERSION_JSON
                COMMAND_ERROR_IS_FATAL ANY
```

Thanks and best regards!

**Comment by cremfert** [comment]
Hint: If I change the code to this:
```
#execute_process(COMMAND "${DART}" run
#                "${CMAKE_CURRENT_SOURCE_DIR}/../libsodium_version.dart"
#                OUTPUT_VARIABLE LIBSODIUM_VERSION_JSON
#                COMMAND_ERROR_IS_FATAL ANY
#)
set(LIBSODIUM_VERSION_JSON "{\"ffi\":\"1.0.18\",\"js\":\"0.7.9\"}")
```
(so adding manually the version information), everything works fine! It seems like dart cannot be executed from the CMake file. Any ideas, what the problem could be?

Thanks and best regards!

**Comment by Skycoder42** [comment]
Huh, that is weird. Is the dart executable available in your PATH? What happens if you run `dart --version` in the same command prompt as the one where you run the build? However, the check in https://github.com/Skycoder42/libsodium_dart_bindings/blob/main/packages/sodium_libs/windows/CMakeLists.txt#L16 should already fail if dart was not found. Which CMake version are you using?

If thats not it, I am not sure where the problem is. In the CI-Pipeline, the build succeeds. Maybe you could replace the find program check with the following:
```cmake
if(DART)
  message("Found dart at: ${DART}")
else()
if(NOT DART)
  message(FATAL_ERROR "Did not find dart in PATH!")
endif()
```

Also, running `flutter build ... --verbose` might output something useful, so it's worth a try.

**Comment by cremfert** [comment]
I will check tomorrow - the dart executable is in the PATH, I can call ```dart --version``` so this shouldn't be the problem. Looks like the CMAKE process runs in a thread that does not have access to the path.

The error also does not say, that dart isn't available but that dart isn't a valid Win32 application.

I think it could be an issue with Win 11 and Visual Studio 2022 - would it be ok for you to tell me your Windows Version (10?) and the Visual Studio Version you are running? Then I will set up a VM and test it there.

Thanks a lot!

**Comment by Skycoder42** [comment]
I am using the GitHub Actions CI with the `windows-latest` image. You can find more information on the image, including OS-Version and more here: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

I have not tested it on Windows 11 yet, so that might be the reason. And yes, the error message seems to indicate that cmake fails to pass the correct dart path to the subshell executing the command.

**Comment by cremfert** [comment]
I just changed the code to:
```execute_process(COMMAND "c:\\flutter\\bin\\cache\\dart-sdk\\bin\\dart.exe" run```
now, it works - it seems like CMake resolve the dart.exe to something else, in my case to "C:\\flutter\\bin". Maybe I need to change my path then...

**Comment by Skycoder42** [comment]
That is weird. As far as I know, the dart executable is "linked" in the `C:\flutter\bin` directory (If I remember correctly, as a batch script), so that path should work as well. But maybe the execute_process cannot directly execute a script, that could be an explanation. Does your `C:\flutter\bin` contain a dart executable/script?

I also looked at the documentation of exec_program, and apparently, it is deprecated and should not be used anymore: https://cmake.org/cmake/help/v3.0/command/exec_program.html#command:exec_program

So I am unsure if I should actually use it. I think, maybe just explicitly using a shell (`cmd /c "${DART}"`) might be enough.

**Comment by cremfert** [comment]
I tried with ```cmd /c {DART}``` but it says: "The file cannot be found." :(

**Comment by cremfert** [comment]
![Bildschirmfoto 2022-03-29 um 12 21 02](https://user-images.githubusercontent.com/1306390/160590654-45c10639-3202-428d-b620-74a1dfe044a6.png)

This is my flutter\bin folder.

**Comment by Skycoder42** [comment]
Okay, so I updated the native flutter parts of the plugin and changed the windows build to use "cmd /c ${dart} ...". The pipeline succeeds, so it seams to at least generally work.

Could you try the build with the lastest main branch? You can simply use a git-dependency in the pubspec for that:
```yaml
dependencies:
  sodium_libs:
    git:
      url: https://github.com/Skycoder42/libsodium_dart_bindings.git
      ref: main
```

**Comment by Skycoder42** [comment]
So I tried it myself on a Windows 11 Machine with VS 2022 and I can build successfully. Did the changes on the master branch fix your problem?

**Comment by cremfert** [comment]
Sorry for the delay, I'm currently traveling, but will have a look on it next week and give feedback! Thanks a lot for your effort!

**Comment by cremfert** [comment]
Yes, it works - thank you so much for your help and support with this!

**Comment by Skycoder42** [comment]
perfekt, then I will publish that soon
